apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["sh","-c"]
    args: ["echo \" Conatiner1\" >> /data/file.txt", "Sleep 3000"]
    volumeMounts:
    - mountPath: /data/
      name: my-pv
  - name: container2
    image: ubuntu
    command: ["sh","-c"]
    args: ["echo \" Conatiner2\" >> /data/file.txt", "Sleep 3000"]
    volumeMounts:
    - mountPath: /data/
      name: my-pv
  - name: container3
    image: ubuntu
    command: ["sh","-c"]
    args: ["cat /data/file.txt", "Sleep 3000"]
    volumeMounts:
    - mountPath: /data/
      name: my-pv
  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: my-pvc
